# This is a basic workflow to help you get started with Actions
name: DeathTax Update

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  repository_dispatch:
    types: [script-update]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout master
        uses: actions/checkout@v2

      - name: Checkout submodules
        uses: textbook/git-checkout-submodule-action@master
        with:
          remote: true
      
      - name: push
        uses: github-actions-x/commit@master
        with:
          github-token: ${{ secrets.REPO_ACCESS_TOKEN }}
          push-branch: 'master'
          commit-message: 'Update DeathTax script'
          force-add: 'true'
          files: DeathTax/
          name: Kwazii
          email: kayoticsully@gmail.com
